a = int(input())
b = int(input())
c = int(input())
num = a*b*c
num = str(num)
# print(num)

print(num.count("0"))
print(num.count("1"))
print(num.count("2"))
print(num.count("3"))
print(num.count("4"))
print(num.count("5"))
print(num.count("6"))
print(num.count("7"))
print(num.count("8"))
print(num.count("9"))
